version: '3.8'

services:
  postgres: 
    image: postgres:12.2
    restart: always
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: muv
    networks:
      - outside

  pg_admin: 
    image: dpage/pgadmin4
    restart: always
    ports: 
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "jorge@semantic.mx"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    depends_on:
      - postgres
    networks:
      - outside


networks:
  outside:
    name: prestashop-net
    external: true
